[package]
name = "custom-time"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }

[[bin]]
name = "custom-time"
path = "main.rs"

[profile.release]
# lto = true
# strip = true
# opt-level = 3
# panic = "abort"
# codegen-units = 1
